/**
 * CANIT Skope - Preloaded Baseline Datasets
 * Neutral Demo Performance Intelligence Dataset
 * Phase 2: Normalized ReportingPeriod architecture with multi-channel conversion metrics
 */

export const INITIAL_REPORTS = [
  {
    reportId: 'cnd_rep_2026_M09_W03',
    periodName: 'Week 3 · Sep 14–20, 2026',
    period: {
      periodId: '2026_M09_W03',
      year: 2026,
      month: 'September',
      monthNumber: 9,
      weekNumber: 3,
      startDate: '2026-09-14',
      endDate: '2026-09-20',
      periodLabel: 'Week 3 · Sep 14–20, 2026',
      isMonthlyAggregate: false
    },
    uploadedAt: '2026-09-21T10:00:00Z',
    sourceType: 'system-demo',
    sourceFileName: 'CANIT_Performance_Intelligence.csv',
    status: 'Ready',
    budgetSummary: {
      allocated: 238981,
      spent: 191185,
      remaining: 47796,
      dailyRunRate: 27312,
      historicalDailyAvg: 25127,
      spendRatePercent: 80.0
    },
    metrics: {
      spend: 191185,
      totalSpend: 191185,
      impressions: 436475,
      clicks: 24346,
      ctr: 5.58,
      cpc: 7.85,
      leads: 211,
      conversions: 189,
      sourceResults: 262,
      phoneCalls: 51,
      allConversions: 240,
      allConversionsDerived: true,
      cpa: 1012,
      costPerAllConv: 797,
      conversionRate: 0.99
    },
    campaigns: [
      {
        id: 'cnd_search_core_w3',
        name: 'CANIT - High Intent Core Search',
        platform: 'google',
        channel: 'Search',
        specialty: 'Brand & Platform Search',
        section: 'Google Search',
        spend: 48875,
        impressions: 32660,
        clicks: 3048,
        cpc: 16.03,
        ctr: 9.33,
        leads: 48,
        conversions: 44,
        sourceResults: 60,
        phoneCalls: 16,
        allConversions: 60,
        allConversionsDerived: true,
        cpa: 1111,
        costPerAllConv: 815,
        conversionRate: 1.97,
        classification: 'strong',
        rank: 1,
        notes: 'Top performing direct intent search campaign with high conversion volume.'
      },
      {
        id: 'cnd_pmax_growth_w3',
        name: 'CANIT - Omnichannel Growth PMax',
        platform: 'google',
        channel: 'PMax',
        specialty: 'Growth & Conversion',
        section: 'Google PMax / Video',
        spend: 43930,
        impressions: 163300,
        clicks: 9028,
        cpc: 4.87,
        ctr: 5.53,
        leads: 63,
        conversions: 60,
        sourceResults: 85,
        phoneCalls: 25,
        allConversions: 85,
        allConversionsDerived: true,
        cpa: 732,
        costPerAllConv: 517,
        conversionRate: 0.94,
        classification: 'strong',
        rank: 2,
        notes: 'High-velocity omnichannel campaign delivering efficient cost-per-acquisition.'
      },
      {
        id: 'cnd_search_enterprise_w3',
        name: 'CANIT - Enterprise Solutions Search',
        platform: 'google',
        channel: 'Search',
        specialty: 'Enterprise B2B',
        section: 'Google Search',
        spend: 36570,
        impressions: 18630,
        clicks: 1288,
        cpc: 28.39,
        ctr: 6.91,
        leads: 21,
        conversions: 18,
        sourceResults: 27,
        phoneCalls: 9,
        allConversions: 27,
        allConversionsDerived: true,
        cpa: 2032,
        costPerAllConv: 1354,
        conversionRate: 2.10,
        classification: 'strong',
        rank: 3,
        notes: 'Targeted search capturing enterprise decision makers.'
      },
      {
        id: 'cnd_meta_leadgen_w3',
        name: 'CANIT - Lead Gen & Retargeting [Meta]',
        platform: 'meta',
        channel: 'Social Lead Gen',
        specialty: 'Mid-Funnel Retargeting',
        section: 'Meta Ads',
        spend: 30360,
        impressions: 78775,
        clicks: 3933,
        cpc: 7.72,
        ctr: 4.99,
        leads: 55,
        conversions: 51,
        sourceResults: 65,
        phoneCalls: 14,
        allConversions: 65,
        allConversionsDerived: true,
        cpa: 595,
        costPerAllConv: 467,
        conversionRate: 1.65,
        classification: 'strong',
        rank: 4,
        notes: 'Meta retargeting ads driving high-intent demo requests.'
      },
      {
        id: 'cnd_meta_discovery_w3',
        name: 'CANIT - Social Brand Discovery [Meta]',
        platform: 'meta',
        channel: 'Social Awareness',
        specialty: 'Top-of-Funnel Brand',
        section: 'Meta Ads',
        spend: 16675,
        impressions: 98210,
        clicks: 4773,
        cpc: 3.49,
        ctr: 4.86,
        leads: 14,
        conversions: 9,
        sourceResults: 14,
        phoneCalls: 5,
        allConversions: 14,
        allConversionsDerived: true,
        cpa: 1853,
        costPerAllConv: 1191,
        conversionRate: 0.29,
        classification: 'neutral',
        rank: 5,
        notes: 'Broad social awareness driving brand discovery.'
      },
      {
        id: 'cnd_youtube_video_w3',
        name: 'CANIT - Product Demo Video [YouTube]',
        platform: 'google',
        channel: 'Video',
        specialty: 'Video Engagement',
        section: 'Google PMax / Video',
        spend: 14720,
        impressions: 59800,
        clicks: 2277,
        cpc: 6.46,
        ctr: 3.81,
        leads: 9,
        conversions: 7,
        sourceResults: 9,
        phoneCalls: 2,
        allConversions: 9,
        allConversionsDerived: true,
        cpa: 2103,
        costPerAllConv: 1636,
        conversionRate: 0.40,
        classification: 'neutral',
        rank: 6,
        notes: 'Short explainer video ads explaining platform intelligence features.'
      }
    ]
  },
  {
    reportId: 'cnd_rep_2026_M09_W02',
    periodName: 'Week 2 · Sep 07–13, 2026',
    period: {
      periodId: '2026_M09_W02',
      year: 2026,
      month: 'September',
      monthNumber: 9,
      weekNumber: 2,
      startDate: '2026-09-07',
      endDate: '2026-09-13',
      periodLabel: 'Week 2 · Sep 07–13, 2026',
      isMonthlyAggregate: false
    },
    uploadedAt: '2026-09-14T10:00:00Z',
    sourceType: 'system-demo',
    sourceFileName: 'CANIT_Performance_Intelligence.csv',
    status: 'Ready',
    budgetSummary: {
      allocated: 218182,
      spent: 174545,
      remaining: 43637,
      dailyRunRate: 24935,
      historicalDailyAvg: 23100,
      spendRatePercent: 80.0
    },
    metrics: {
      spend: 174545,
      totalSpend: 174545,
      impressions: 398500,
      clicks: 22230,
      ctr: 5.58,
      cpc: 7.85,
      leads: 192,
      conversions: 172,
      sourceResults: 238,
      phoneCalls: 46,
      allConversions: 218,
      allConversionsDerived: true,
      cpa: 1015,
      costPerAllConv: 801,
      conversionRate: 0.98
    },
    campaigns: [
      {
        id: 'cnd_search_core_w2',
        name: 'CANIT - High Intent Core Search',
        platform: 'google',
        channel: 'Search',
        specialty: 'Brand & Platform Search',
        section: 'Google Search',
        spend: 44625,
        impressions: 29820,
        clicks: 2783,
        cpc: 16.03,
        ctr: 9.33,
        leads: 44,
        conversions: 40,
        sourceResults: 55,
        phoneCalls: 15,
        allConversions: 55,
        allConversionsDerived: true,
        cpa: 1116,
        costPerAllConv: 811,
        conversionRate: 1.98,
        classification: 'strong',
        rank: 1,
        notes: 'Consistent top of funnel acquisition.'
      },
      {
        id: 'cnd_pmax_growth_w2',
        name: 'CANIT - Omnichannel Growth PMax',
        platform: 'google',
        channel: 'PMax',
        specialty: 'Growth & Conversion',
        section: 'Google PMax / Video',
        spend: 40110,
        impressions: 149100,
        clicks: 8243,
        cpc: 4.87,
        ctr: 5.53,
        leads: 58,
        conversions: 55,
        sourceResults: 78,
        phoneCalls: 23,
        allConversions: 78,
        allConversionsDerived: true,
        cpa: 729,
        costPerAllConv: 514,
        conversionRate: 0.95,
        classification: 'strong',
        rank: 2,
        notes: 'Low CPA driver.'
      },
      {
        id: 'cnd_search_enterprise_w2',
        name: 'CANIT - Enterprise Solutions Search',
        platform: 'google',
        channel: 'Search',
        specialty: 'Enterprise B2B',
        section: 'Google Search',
        spend: 33390,
        impressions: 17010,
        clicks: 1176,
        cpc: 28.39,
        ctr: 6.91,
        leads: 19,
        conversions: 17,
        sourceResults: 25,
        phoneCalls: 8,
        allConversions: 25,
        allConversionsDerived: true,
        cpa: 1964,
        costPerAllConv: 1336,
        conversionRate: 2.13,
        classification: 'strong',
        rank: 3,
        notes: 'High intent pipeline generator.'
      },
      {
        id: 'cnd_meta_leadgen_w2',
        name: 'CANIT - Lead Gen & Retargeting [Meta]',
        platform: 'meta',
        channel: 'Social Lead Gen',
        specialty: 'Mid-Funnel Retargeting',
        section: 'Meta Ads',
        spend: 27720,
        impressions: 71925,
        clicks: 3591,
        cpc: 7.72,
        ctr: 4.99,
        leads: 50,
        conversions: 46,
        sourceResults: 59,
        phoneCalls: 13,
        allConversions: 59,
        allConversionsDerived: true,
        cpa: 603,
        costPerAllConv: 470,
        conversionRate: 1.64,
        classification: 'strong',
        rank: 4,
        notes: 'Social acquisition steady.'
      },
      {
        id: 'cnd_meta_discovery_w2',
        name: 'CANIT - Social Brand Discovery [Meta]',
        platform: 'meta',
        channel: 'Social Awareness',
        specialty: 'Top-of-Funnel Brand',
        section: 'Meta Ads',
        spend: 15225,
        impressions: 89670,
        clicks: 4358,
        cpc: 3.49,
        ctr: 4.86,
        leads: 13,
        conversions: 8,
        sourceResults: 12,
        phoneCalls: 4,
        allConversions: 12,
        allConversionsDerived: true,
        cpa: 1903,
        costPerAllConv: 1269,
        conversionRate: 0.28,
        classification: 'neutral',
        rank: 5,
        notes: 'Audience expansion testing.'
      },
      {
        id: 'cnd_youtube_video_w2',
        name: 'CANIT - Product Demo Video [YouTube]',
        platform: 'google',
        channel: 'Video',
        specialty: 'Video Engagement',
        section: 'Google PMax / Video',
        spend: 13440,
        impressions: 54600,
        clicks: 2079,
        cpc: 6.46,
        ctr: 3.81,
        leads: 8,
        conversions: 6,
        sourceResults: 8,
        phoneCalls: 2,
        allConversions: 8,
        allConversionsDerived: true,
        cpa: 2240,
        costPerAllConv: 1680,
        conversionRate: 0.38,
        classification: 'neutral',
        rank: 6,
        notes: 'Video completion rate at 42%.'
      }
    ]
  }
];

export const INITIAL_RECOMMENDATIONS = [
  {
    id: 'rec_pillar_1',
    pillar: 'Pillar 1: Stop Inefficient Budget Leakage',
    title: 'Prune Broad Match Search Queries & Enforce Exact-Match Keyword Groups',
    campaignTarget: 'CANIT - High Intent Core Search, Enterprise Solutions Search',
    problem: 'Broad match terms captured low-intent exploratory traffic, causing 18% CPC inflation.',
    recommendation: 'Migrate core high-converting keywords strictly to phrase & exact match. Implement negative keyword list for irrelevant job/informational queries.',
    reason: 'Eliminates wasted spend and drives down average search CPC by up to 25%.',
    priority: 'critical',
    owner: 'PPC Lead',
    status: 'active',
    impactEstimate: '₹35,000 / month saved',
    customNotes: 'Negative keyword list updated weekly.',
    updatedAt: '2026-09-20T12:00:00Z'
  },
  {
    id: 'rec_pillar_2',
    pillar: 'Pillar 2: Scale High-Yielding Omnichannel Channels',
    title: 'Scale Omnichannel Growth PMax Budget by 30%',
    campaignTarget: 'CANIT - Omnichannel Growth PMax',
    problem: 'Our most efficient conversion engine (CPA under ₹750) is hitting daily budget caps by 6 PM.',
    recommendation: 'Increase daily budget cap on Performance Max campaign to capture unmet evening search and display demand.',
    reason: 'PMax delivers our lowest blended acquisition cost across Google properties.',
    priority: 'critical',
    owner: 'Growth Manager',
    status: 'active',
    impactEstimate: '+50 Qualified Leads / Month',
    customNotes: 'Budget expansion scheduled across next sprint.',
    updatedAt: '2026-09-20T12:00:00Z'
  },
  {
    id: 'rec_pillar_3',
    pillar: 'Pillar 3: Optimize Social Conversion Funnels',
    title: 'Deploy Interactive Lead Forms on Meta Retargeting Ads',
    campaignTarget: 'CANIT - Lead Gen & Retargeting [Meta]',
    problem: 'External landing page redirects on mobile social ads introduce 30% dropoff.',
    recommendation: 'Use Meta Native Instant Forms with CRM auto-sync to eliminate page loading friction.',
    reason: 'Native lead forms typically lift submission conversion rates by 35-50% on mobile.',
    priority: 'high',
    owner: 'Social Media Lead',
    status: 'in_progress',
    impactEstimate: '+40% Mobile Lead Form Submissions',
    customNotes: 'Integration webhook active in staging.',
    updatedAt: '2026-09-20T14:30:00Z'
  },
  {
    id: 'rec_pillar_4',
    pillar: 'Pillar 4: Creative Refresh & Video Hook Testing',
    title: 'Iterate YouTube Product Demo Hooks with Dynamic Problem/Solution Intros',
    campaignTarget: 'CANIT - Product Demo Video [YouTube]',
    problem: 'First 5-second viewer drop-off on video campaigns is currently 42%.',
    recommendation: 'Test 3 new 5-second hook variations highlighting automated executive reporting to improve view-through rate.',
    reason: 'Higher retention signals lower CPMs and improves downstream search intent.',
    priority: 'medium',
    owner: 'Creative Director',
    status: 'active',
    impactEstimate: 'Est. 20% Reduction in Video CPM',
    customNotes: 'New creative cuts ready for A/B rollout.',
    updatedAt: '2026-09-20T15:00:00Z'
  }
];

export const AI_SYNTHESIS_BASE = {
  sprintScore: 91,
  totalIdentifiedWaste: 28400,
  projectedTargetConversions: 250,
  executiveBrief: "The current advertising cycle demonstrates strong multi-channel synergy. Google Search captures high-intent demand with a 9.3% CTR, while Performance Max and Meta Lead Gen deliver high volume at sub-₹1,000 CPA. Scaling PMax budget and shifting Meta campaigns to instant forms will comfortably exceed monthly acquisition targets.",
  insights: [
    {
      id: 'insight_channel_arbitrage',
      category: 'channel_divergence',
      severity: 'positive',
      badge: 'Channel Efficiency',
      title: 'Performance Max CPA 45% Lower than Enterprise Search',
      metricSummary: 'PMax ₹732 CPA vs Enterprise Search ₹2,032 CPA',
      narrative: 'Omnichannel PMax is effectively capturing demand across YouTube, Discovery, and Search with exceptional cost-efficiency.',
      action: 'Scale daily budget allocation to PMax.'
    },
    {
      id: 'insight_social_velocity',
      category: 'waste',
      severity: 'positive',
      badge: 'Retargeting Surge',
      title: 'Meta Retargeting Delivering 50+ Inquiries Weekly',
      metricSummary: 'Meta Retargeting CPA ₹595 with 1.65% conversion rate',
      narrative: 'Mid-funnel social retargeting continues to show compounding returns for warm audiences.',
      action: 'Refresh ad creatives to combat ad fatigue.'
    },
    {
      id: 'insight_waste_quantified',
      category: 'waste',
      severity: 'warning',
      badge: 'Search Term Leakage',
      title: 'Broad Match Search Terms Consuming ₹28.4k Inefficiently',
      metricSummary: '₹28,400 spent on low-relevance exploratory queries',
      narrative: 'Search term report reveals exploratory non-intent search queries inflating cost-per-click.',
      action: 'Add phrase and negative match keyword exclusions.'
    }
  ]
};
