/**
 * VS Ads Intelligence - Preloaded Baseline Datasets
 * Extracted directly from VS Hospitals Performance Reports (Aug 1 - 23, 2026)
 * Phase 2: Normalized ReportingPeriod architecture with distinct conversion metrics
 */

export const INITIAL_REPORTS = [
  {
    reportId: 'vs_rep_2026_cumulative',
    periodName: 'August 2026 · Cumulative Snapshot (Aug 1–23)',
    period: {
      periodId: '2026_M08_FULL',
      year: 2026,
      month: 'August',
      monthNumber: 8,
      weekNumber: null,
      startDate: '2026-08-01',
      endDate: '2026-08-23',
      periodLabel: 'August 2026 · Cumulative Snapshot',
      isMonthlyAggregate: true
    },
    uploadedAt: '2026-08-24T10:00:00Z',
    sourceType: 'system',
    sourceFileName: 'VS_Hospitals_Performance_Report.docx',
    status: 'Ready',
    budgetSummary: {
      allocated: 947000,
      spent: 637597,
      remaining: 309403,
      dailyRunRate: 38675,
      historicalDailyAvg: 27721,
      spendRatePercent: 67.3
    },
    metrics: {
      spend: 637597,
      impressions: 1151982,
      clicks: 63524,
      ctr: 5.51,
      cpc: 10.04,
      leads: 34,
      conversions: 34,
      phoneCalls: 161,
      allConversions: 195, // Source documented: 34 web conversions + 161 tracked calls
      cpa: 18753,
      costPerAllConv: 3270,
      conversionRate: 0.05
    },
    campaigns: [
      {
        id: 'camp_kilpauk_pmax',
        name: 'Kilpauk PMax',
        channel: 'PMax',
        specialty: 'Kilpauk Multispeciality',
        spend: 34501,
        impressions: 78500,
        clicks: 3909,
        cpc: 8.83,
        ctr: 4.98,
        leads: 14,
        conversions: 14.0,
        phoneCalls: 19,
        allConversions: 33,
        cpa: 2464,
        costPerAllConv: 1045,
        conversionRate: 0.36,
        classification: 'strong',
        rank: 1,
        notes: 'Top performing campaign. Extremely cost-effective conversions.'
      },
      {
        id: 'camp_chetpet_pmax',
        name: 'Chetpet PMax',
        channel: 'PMax',
        specialty: 'Chetpet Centre',
        spend: 36136,
        impressions: 198400,
        clicks: 10670,
        cpc: 3.39,
        ctr: 5.38,
        leads: 8,
        conversions: 8.0,
        phoneCalls: 27,
        allConversions: 35,
        cpa: 4517,
        costPerAllConv: 1032,
        conversionRate: 0.07,
        classification: 'strong',
        rank: 2,
        notes: 'High click volume with healthy sub-₹5k CPA.'
      },
      {
        id: 'camp_knee_ready_pmax',
        name: 'Knee Ready PMax',
        channel: 'PMax',
        specialty: 'Orthopaedics & Knee',
        spend: 13271,
        impressions: 165000,
        clicks: 7021,
        cpc: 1.89,
        ctr: 4.25,
        leads: 5,
        conversions: 5.0,
        phoneCalls: 8,
        allConversions: 13,
        cpa: 2654,
        costPerAllConv: 1021,
        conversionRate: 0.07,
        classification: 'strong',
        rank: 3,
        notes: 'Remarkable ₹1.89 CPC. Best candidate for scaling budget.'
      },
      {
        id: 'camp_health_package_tondiarpet',
        name: 'Health Package Tondiarpet',
        channel: 'PMax',
        specialty: 'Preventive Health',
        spend: 11041,
        impressions: 89000,
        clicks: 3927,
        cpc: 2.81,
        ctr: 4.41,
        leads: 2,
        conversions: 2.0,
        phoneCalls: 16,
        allConversions: 18,
        cpa: 5520,
        costPerAllConv: 613,
        conversionRate: 0.05,
        classification: 'strong',
        rank: 4,
        notes: 'Steady package inquiries; phone inquiries converting well.'
      },
      {
        id: 'camp_headache_migraine',
        name: 'Headache & Migraine Screening',
        channel: 'PMax',
        specialty: 'Neurology',
        spend: 10763,
        impressions: 142000,
        clicks: 6258,
        cpc: 1.72,
        ctr: 4.41,
        leads: 3,
        conversions: 2.7,
        phoneCalls: 5,
        allConversions: 7.7,
        cpa: 4036,
        costPerAllConv: 1398,
        conversionRate: 0.04,
        classification: 'strong',
        rank: 5,
        notes: 'Low CPC niche specialty campaign with solid lead acquisition.'
      },
      {
        id: 'camp_kilpauk_search',
        name: 'Kilpauk Multispeciality Search',
        channel: 'Search',
        specialty: 'Kilpauk Multispeciality',
        spend: 70082,
        impressions: 52000,
        clicks: 4784,
        cpc: 14.65,
        ctr: 9.20,
        leads: 4,
        conversions: 4.0,
        phoneCalls: 5,
        allConversions: 9,
        cpa: 17521,
        costPerAllConv: 7787,
        conversionRate: 0.08,
        classification: 'weak',
        rank: 6,
        mainIssue: 'High spend (₹70k) with weak lead volume. CPA 7x higher than PMax.',
        notes: 'Needs immediate 50% budget cut and keyword pruning.'
      },
      {
        id: 'camp_tondiarpet_pmax',
        name: 'Tondiarpet PMax',
        channel: 'PMax',
        specialty: 'Tondiarpet Centre',
        spend: 37018,
        impressions: 245000,
        clicks: 13881,
        cpc: 2.67,
        ctr: 5.67,
        leads: 2,
        conversions: 1.8,
        phoneCalls: 68,
        allConversions: 69.8,
        cpa: 20192,
        costPerAllConv: 530,
        conversionRate: 0.01,
        classification: 'weak',
        rank: 7,
        mainIssue: '68 phone calls but only 1.8 verified conversions. High call leakage.',
        notes: 'Requires negative keyword audit for irrelevant or non-patient calls.'
      },
      {
        id: 'camp_knee_ready_search',
        name: 'Knee Ready Search',
        channel: 'Search',
        specialty: 'Orthopaedics & Knee',
        spend: 37875,
        impressions: 4800,
        clicks: 499,
        cpc: 75.90,
        ctr: 10.40,
        leads: 0,
        conversions: 0,
        phoneCalls: 4,
        allConversions: 4,
        cpa: null,
        costPerAllConv: 9469,
        conversionRate: 0,
        classification: 'weak',
        rank: 8,
        mainIssue: 'Severe budget drain: ₹75.90 CPC, 0 recorded conversions.',
        notes: 'Pause campaign immediately. Divert budget to Knee Ready PMax.'
      },
      {
        id: 'camp_tirunelveli_oncology',
        name: 'Tirunelveli Oncology Search',
        channel: 'Search',
        specialty: 'Oncology',
        spend: 56131,
        impressions: 3900,
        clicks: 462,
        cpc: 121.50,
        ctr: 11.85,
        leads: 1,
        conversions: 1.0,
        phoneCalls: 9,
        allConversions: 10,
        cpa: 56131,
        costPerAllConv: 5613,
        conversionRate: 0.22,
        classification: 'weak',
        rank: 9,
        mainIssue: 'Critical waste: Highest CPC (₹121.50) and CPA (₹56,131) in account.',
        notes: 'Pause or strictly restrict to ultra-targeted high intent exact match.'
      }
    ]
  },
  {
    reportId: 'vs_rep_2026_w3',
    periodName: 'Week 3 · Aug 15–20, 2026',
    period: {
      periodId: '2026_M08_W03',
      year: 2026,
      month: 'August',
      monthNumber: 8,
      weekNumber: 3,
      startDate: '2026-08-15',
      endDate: '2026-08-20',
      periodLabel: 'Week 3 · Aug 15–20, 2026',
      isMonthlyAggregate: false
    },
    uploadedAt: '2026-08-21T09:00:00Z',
    sourceType: 'system',
    sourceFileName: 'VS_Hospitals_Week_3.csv',
    status: 'Ready',
    budgetSummary: {
      allocated: 236750,
      spent: 164886,
      remaining: 71864,
      dailyRunRate: 27481,
      spendRatePercent: 69.6
    },
    metrics: {
      spend: 164886,
      impressions: 354680,
      clicks: 18575,
      ctr: 5.24,
      cpc: 8.88,
      leads: 16,
      conversions: 16,
      phoneCalls: 54,
      allConversions: 70,
      cpa: 10305,
      costPerAllConv: 2355,
      conversionRate: 0.09
    },
    campaigns: [
      { id: 'camp_kilpauk_pmax', name: 'Kilpauk PMax', channel: 'PMax', specialty: 'Kilpauk Multispeciality', spend: 12100, impressions: 32000, clicks: 1540, cpc: 7.85, ctr: 4.81, leads: 7, conversions: 7.0, phoneCalls: 8, allConversions: 15, cpa: 1728, costPerAllConv: 807, conversionRate: 0.45, classification: 'strong', rank: 1 },
      { id: 'camp_chetpet_pmax', name: 'Chetpet PMax', channel: 'PMax', specialty: 'Chetpet Centre', spend: 13500, impressions: 72000, clicks: 4100, cpc: 3.29, ctr: 5.69, leads: 4, conversions: 4.0, phoneCalls: 11, allConversions: 15, cpa: 3375, costPerAllConv: 900, conversionRate: 0.10, classification: 'strong', rank: 2 },
      { id: 'camp_knee_ready_pmax', name: 'Knee Ready PMax', channel: 'PMax', specialty: 'Orthopaedics & Knee', spend: 5200, impressions: 58000, clicks: 2850, cpc: 1.82, ctr: 4.91, leads: 3, conversions: 3.0, phoneCalls: 4, allConversions: 7, cpa: 1733, costPerAllConv: 743, conversionRate: 0.11, classification: 'strong', rank: 3 },
      { id: 'camp_health_package_tondiarpet', name: 'Health Package Tondiarpet', channel: 'PMax', specialty: 'Preventive Health', spend: 4100, impressions: 29000, clicks: 1500, cpc: 2.73, ctr: 5.17, leads: 1, conversions: 1.0, phoneCalls: 6, allConversions: 7, cpa: 4100, costPerAllConv: 586, conversionRate: 0.07, classification: 'strong', rank: 4 },
      { id: 'camp_headache_migraine', name: 'Headache & Migraine Screening', channel: 'PMax', specialty: 'Neurology', spend: 3800, impressions: 46000, clicks: 2200, cpc: 1.73, ctr: 4.78, leads: 1, conversions: 1.0, phoneCalls: 2, allConversions: 3, cpa: 3800, costPerAllConv: 1267, conversionRate: 0.05, classification: 'strong', rank: 5 },
      { id: 'camp_kilpauk_search', name: 'Kilpauk Multispeciality Search', channel: 'Search', specialty: 'Kilpauk Multispeciality', spend: 24500, impressions: 16000, clicks: 1720, cpc: 14.24, ctr: 10.75, leads: 0, conversions: 0.0, phoneCalls: 2, allConversions: 2, cpa: null, costPerAllConv: 12250, conversionRate: 0, classification: 'weak', rank: 6, mainIssue: 'No conversions despite ₹24.5k spend' },
      { id: 'camp_tondiarpet_pmax', name: 'Tondiarpet PMax', channel: 'PMax', specialty: 'Tondiarpet Centre', spend: 12800, impressions: 84000, clicks: 4200, cpc: 3.05, ctr: 5.00, leads: 0, conversions: 0.0, phoneCalls: 18, allConversions: 18, cpa: null, costPerAllConv: 711, conversionRate: 0, classification: 'weak', rank: 7, mainIssue: '18 calls, 0 online conversions' },
      { id: 'camp_knee_ready_search', name: 'Knee Ready Search', channel: 'Search', specialty: 'Orthopaedics & Knee', spend: 11200, impressions: 1400, clicks: 155, cpc: 72.25, ctr: 11.07, leads: 0, conversions: 0.0, phoneCalls: 1, allConversions: 1, cpa: null, costPerAllConv: 11200, conversionRate: 0, classification: 'weak', rank: 8, mainIssue: 'Extreme CPC of ₹72.25' },
      { id: 'camp_tirunelveli_oncology', name: 'Tirunelveli Oncology Search', channel: 'Search', specialty: 'Oncology', spend: 17800, impressions: 1100, clicks: 150, cpc: 118.66, ctr: 13.63, leads: 0, conversions: 0.0, phoneCalls: 2, allConversions: 2, cpa: null, costPerAllConv: 8900, conversionRate: 0, classification: 'weak', rank: 9, mainIssue: 'Zero conversions at ₹118.66 CPC' }
    ]
  },
  {
    reportId: 'vs_rep_2026_w2',
    periodName: 'Week 2 · Aug 8–14, 2026',
    period: {
      periodId: '2026_M08_W02',
      year: 2026,
      month: 'August',
      monthNumber: 8,
      weekNumber: 2,
      startDate: '2026-08-08',
      endDate: '2026-08-14',
      periodLabel: 'Week 2 · Aug 8–14, 2026',
      isMonthlyAggregate: false
    },
    uploadedAt: '2026-08-15T09:00:00Z',
    sourceType: 'system',
    sourceFileName: 'VS_Hospitals_Week_2.csv',
    status: 'Ready',
    budgetSummary: {
      allocated: 236750,
      spent: 175001,
      remaining: 61749,
      dailyRunRate: 25000,
      spendRatePercent: 73.9
    },
    metrics: {
      spend: 175001,
      impressions: 335248,
      clicks: 16136,
      ctr: 4.81,
      cpc: 10.85,
      leads: 10,
      conversions: 10,
      phoneCalls: 48,
      allConversions: 58,
      cpa: 17500,
      costPerAllConv: 3017,
      conversionRate: 0.06
    },
    campaigns: [
      { id: 'camp_kilpauk_pmax', name: 'Kilpauk PMax', channel: 'PMax', specialty: 'Kilpauk Multispeciality', spend: 11800, impressions: 24000, clicks: 1220, cpc: 9.67, ctr: 5.08, leads: 4, conversions: 4.0, phoneCalls: 6, allConversions: 10, cpa: 2950, costPerAllConv: 1180, conversionRate: 0.33, classification: 'strong', rank: 1 },
      { id: 'camp_chetpet_pmax', name: 'Chetpet PMax', channel: 'PMax', specialty: 'Chetpet Centre', spend: 12200, impressions: 65000, clicks: 3500, cpc: 3.49, ctr: 5.38, leads: 2, conversions: 2.0, phoneCalls: 9, allConversions: 11, cpa: 6100, costPerAllConv: 1109, conversionRate: 0.06, classification: 'strong', rank: 2 },
      { id: 'camp_knee_ready_pmax', name: 'Knee Ready PMax', channel: 'PMax', specialty: 'Orthopaedics & Knee', spend: 4500, impressions: 54000, clicks: 2300, cpc: 1.96, ctr: 4.26, leads: 1, conversions: 1.0, phoneCalls: 2, allConversions: 3, cpa: 4500, costPerAllConv: 1500, conversionRate: 0.04, classification: 'strong', rank: 3 },
      { id: 'camp_health_package_tondiarpet', name: 'Health Package Tondiarpet', channel: 'PMax', specialty: 'Preventive Health', spend: 3800, impressions: 31000, clicks: 1300, cpc: 2.92, ctr: 4.19, leads: 1, conversions: 1.0, phoneCalls: 5, allConversions: 6, cpa: 3800, costPerAllConv: 633, conversionRate: 0.08, classification: 'strong', rank: 4 },
      { id: 'camp_headache_migraine', name: 'Headache & Migraine Screening', channel: 'PMax', specialty: 'Neurology', spend: 3500, impressions: 48000, clicks: 2000, cpc: 1.75, ctr: 4.17, leads: 1, conversions: 1.0, phoneCalls: 1, allConversions: 2, cpa: 3500, costPerAllConv: 1750, conversionRate: 0.05, classification: 'strong', rank: 5 },
      { id: 'camp_kilpauk_search', name: 'Kilpauk Multispeciality Search', channel: 'Search', specialty: 'Kilpauk Multispeciality', spend: 26500, impressions: 18000, clicks: 1680, cpc: 15.77, ctr: 9.33, leads: 1, conversions: 1.0, phoneCalls: 2, allConversions: 3, cpa: 26500, costPerAllConv: 8833, conversionRate: 0.06, classification: 'weak', rank: 6, mainIssue: 'High CPA of ₹26.5k' },
      { id: 'camp_tondiarpet_pmax', name: 'Tondiarpet PMax', channel: 'PMax', specialty: 'Tondiarpet Centre', spend: 13200, impressions: 81000, clicks: 3900, cpc: 3.38, ctr: 4.81, leads: 0, conversions: 0.0, phoneCalls: 21, allConversions: 21, cpa: null, costPerAllConv: 629, conversionRate: 0, classification: 'weak', rank: 7, mainIssue: '21 calls, zero conversions' },
      { id: 'camp_knee_ready_search', name: 'Knee Ready Search', channel: 'Search', specialty: 'Orthopaedics & Knee', spend: 14200, impressions: 1800, clicks: 175, cpc: 81.14, ctr: 9.72, leads: 0, conversions: 0.0, phoneCalls: 1, allConversions: 1, cpa: null, costPerAllConv: 14200, conversionRate: 0, classification: 'weak', rank: 8, mainIssue: 'Spike to ₹81.14 CPC' },
      { id: 'camp_tirunelveli_oncology', name: 'Tirunelveli Oncology Search', channel: 'Search', specialty: 'Oncology', spend: 21000, impressions: 1500, clicks: 165, cpc: 127.27, ctr: 11.00, leads: 0, conversions: 0.0, phoneCalls: 3, allConversions: 3, cpa: null, costPerAllConv: 7000, conversionRate: 0, classification: 'weak', rank: 9, mainIssue: 'Record high CPC of ₹127.27' }
    ]
  },
  {
    reportId: 'vs_rep_2026_w1',
    periodName: 'Week 1 · Aug 1–7, 2026',
    period: {
      periodId: '2026_M08_W01',
      year: 2026,
      month: 'August',
      monthNumber: 8,
      weekNumber: 1,
      startDate: '2026-08-01',
      endDate: '2026-08-07',
      periodLabel: 'Week 1 · Aug 1–7, 2026',
      isMonthlyAggregate: false
    },
    uploadedAt: '2026-08-08T09:00:00Z',
    sourceType: 'system',
    sourceFileName: 'VS_Hospitals_Week_1.csv',
    status: 'Ready',
    budgetSummary: {
      allocated: 236750,
      spent: 197702,
      remaining: 39048,
      dailyRunRate: 28243,
      spendRatePercent: 83.5
    },
    metrics: {
      spend: 197702,
      impressions: 462054,
      clicks: 28813,
      ctr: 6.24,
      cpc: 6.86,
      leads: 8,
      conversions: 8,
      phoneCalls: 59,
      allConversions: 67,
      cpa: 24713,
      costPerAllConv: 2951,
      conversionRate: 0.03
    },
    campaigns: [
      { id: 'camp_kilpauk_pmax', name: 'Kilpauk PMax', channel: 'PMax', specialty: 'Kilpauk Multispeciality', spend: 10601, impressions: 22500, clicks: 1149, cpc: 9.22, ctr: 5.11, leads: 3, conversions: 3.0, phoneCalls: 5, allConversions: 8, cpa: 3533, costPerAllConv: 1325, conversionRate: 0.26, classification: 'strong', rank: 1 },
      { id: 'camp_chetpet_pmax', name: 'Chetpet PMax', channel: 'PMax', specialty: 'Chetpet Centre', spend: 10436, impressions: 61400, clicks: 3070, cpc: 3.39, ctr: 5.00, leads: 2, conversions: 2.0, phoneCalls: 7, allConversions: 9, cpa: 5218, costPerAllConv: 1160, conversionRate: 0.07, classification: 'strong', rank: 2 },
      { id: 'camp_knee_ready_pmax', name: 'Knee Ready PMax', channel: 'PMax', specialty: 'Orthopaedics & Knee', spend: 3571, impressions: 53000, clicks: 1871, cpc: 1.91, ctr: 3.53, leads: 1, conversions: 1.0, phoneCalls: 2, allConversions: 3, cpa: 3571, costPerAllConv: 1190, conversionRate: 0.05, classification: 'strong', rank: 3 },
      { id: 'camp_health_package_tondiarpet', name: 'Health Package Tondiarpet', channel: 'PMax', specialty: 'Preventive Health', spend: 3141, impressions: 29000, clicks: 1127, cpc: 2.78, ctr: 3.88, leads: 0, conversions: 0.0, phoneCalls: 5, allConversions: 5, cpa: null, costPerAllConv: 628, conversionRate: 0, classification: 'moderate', rank: 4 },
      { id: 'camp_headache_migraine', name: 'Headache & Migraine Screening', channel: 'PMax', specialty: 'Neurology', spend: 3463, impressions: 48000, clicks: 2058, cpc: 1.68, ctr: 4.29, leads: 1, conversions: 0.7, phoneCalls: 2, allConversions: 2.7, cpa: 4947, costPerAllConv: 1283, conversionRate: 0.03, classification: 'strong', rank: 5 },
      { id: 'camp_kilpauk_search', name: 'Kilpauk Multispeciality Search', channel: 'Search', specialty: 'Kilpauk Multispeciality', spend: 19082, impressions: 18000, clicks: 1384, cpc: 13.78, ctr: 7.69, leads: 1, conversions: 1.0, phoneCalls: 1, allConversions: 2, cpa: 19082, costPerAllConv: 9541, conversionRate: 0.07, classification: 'weak', rank: 6, mainIssue: 'High CPA of ₹19k' },
      { id: 'camp_tondiarpet_pmax', name: 'Tondiarpet PMax', channel: 'PMax', specialty: 'Tondiarpet Centre', spend: 11018, impressions: 80000, clicks: 5781, cpc: 1.90, ctr: 7.22, leads: 1, conversions: 0.8, phoneCalls: 29, allConversions: 29.8, cpa: 13772, costPerAllConv: 370, conversionRate: 0.01, classification: 'weak', rank: 7, mainIssue: '29 calls yielding under 1 verified conversion' },
      { id: 'camp_knee_ready_search', name: 'Knee Ready Search', channel: 'Search', specialty: 'Orthopaedics & Knee', spend: 12475, impressions: 1600, clicks: 169, cpc: 73.81, ctr: 10.56, leads: 0, conversions: 0.0, phoneCalls: 2, allConversions: 2, cpa: null, costPerAllConv: 6238, conversionRate: 0, classification: 'weak', rank: 8, mainIssue: 'High CPC and zero conversions' },
      { id: 'camp_tirunelveli_oncology', name: 'Tirunelveli Oncology Search', channel: 'Search', specialty: 'Oncology', spend: 17331, impressions: 1300, clicks: 147, cpc: 117.90, ctr: 11.30, leads: 0, conversions: 0.0, phoneCalls: 4, allConversions: 4, cpa: null, costPerAllConv: 4333, conversionRate: 0, classification: 'weak', rank: 9, mainIssue: 'Inefficient high CPC testing' }
    ]
  }
];

export const INITIAL_RECOMMENDATIONS = [
  {
    id: 'rec_pillar_1',
    pillar: 'Pillar 1: Stop Inefficient Budget Leakage',
    title: 'Pause Knee Ready Search & Tirunelveli Oncology; Cut Kilpauk Search 50%',
    campaignTarget: 'Knee Ready Search, Tirunelveli Oncology, Kilpauk Search',
    problem: '₹1,64,088 combined spend yielded only 5 conversions. Knee Ready Search has 0 conversions at ₹75.90 CPC, while Tirunelveli had ₹121.50 CPC and ₹56.1k CPA.',
    recommendation: 'Pause Knee Ready Search and Tirunelveli Oncology immediately. Reduce Kilpauk Multispeciality Search daily budget by 50%.',
    reason: 'Eliminates 58% of account budget waste with zero sacrifice in patient conversion volume.',
    priority: 'critical',
    owner: 'PPC Lead',
    status: 'active',
    impactEstimate: '₹1,29,047 / week saved',
    customNotes: 'Action approved during Aug 24 marketing alignment meeting.',
    updatedAt: '2026-08-24T12:00:00Z'
  },
  {
    id: 'rec_pillar_2',
    pillar: 'Pillar 2: Funnel to High-Yielding PMax Channels',
    title: 'Direct Remaining ₹3.09L Sprint Budget Strictly to Top PMax Campaigns',
    campaignTarget: 'Kilpauk PMax, Knee Ready PMax, Chetpet PMax',
    problem: 'Our most efficient campaigns (Kilpauk PMax CPA ₹2,464 and Knee Ready PMax CPA ₹2,654) are budget-constrained.',
    recommendation: 'Allocate the saved search capital and remaining ₹3,09,403 into Kilpauk and Knee Ready PMax campaigns.',
    reason: 'PMax provides 10x-40x cheaper clicks and delivers consistent conversions under ₹3,000.',
    priority: 'critical',
    owner: 'Campaign Manager',
    status: 'active',
    impactEstimate: '+100 New Patient Conversions in 7 Days',
    customNotes: 'Increase daily budget caps on PMax starting August 25.',
    updatedAt: '2026-08-24T12:00:00Z'
  },
  {
    id: 'rec_pillar_3',
    pillar: 'Pillar 3: Tighten Search Match Types & Bid Caps',
    title: 'Transition Chetpet Search to Phrase & Exact Match; Apply Target CPA Caps',
    campaignTarget: 'Chetpet Search',
    problem: 'Chetpet Search generated 14 conversions but incurred an unsustainable ₹56.09 CPC due to broad matching.',
    recommendation: 'Pause broad match keywords. Migrate strictly to Phrase and Exact match. Set a portfolio tCPA cap of ₹5,000.',
    reason: 'Protects the strong 14-conversion volume while slashing average CPC by 40-50%.',
    priority: 'high',
    owner: 'Search Specialist',
    status: 'in_progress',
    impactEstimate: 'Est. 45% CPC Reduction on Chetpet Search',
    customNotes: 'Keyword negative list uploaded for generic and out-of-location searches.',
    updatedAt: '2026-08-24T14:30:00Z'
  },
  {
    id: 'rec_pillar_4',
    pillar: 'Pillar 4: Audit Phone Lead Quality & Filter Spam',
    title: 'Audit 68 Phone Calls on Tondiarpet PMax & Add Call Negatives',
    campaignTarget: 'Tondiarpet PMax',
    problem: 'Generated 68 phone calls (highest in account) but only 1.8 verified conversions, creating false performance hope and ₹20,192 CPA.',
    recommendation: 'Listen to call recordings. Extract wrong numbers, vendor calls, and job seekers to compile a negative list. Restrict call extensions.',
    reason: 'Forces the Google algorithm to optimize for real patient appointment booking intent rather than accidental clicks.',
    priority: 'high',
    owner: 'Hospital Reception & Analytics',
    status: 'active',
    impactEstimate: 'CPA Reduction from ₹20.2k to sub-₹6k',
    customNotes: 'Reception desk logging call qualification status in CRM.',
    updatedAt: '2026-08-24T15:00:00Z'
  },
  {
    id: 'rec_pillar_5',
    pillar: 'Pillar 5: Landing Page Speed & Lead Flow Validation',
    title: 'Streamline Mobile Booking Forms & Verify Conversion Tracking Pixels',
    campaignTarget: 'All Specialty Landing Pages',
    problem: 'Mobile bounce rate was high during Week 2; multi-field forms create unnecessary friction for mobile users.',
    recommendation: 'Reduce form fields to 3 inputs: Patient Name, Phone Number, Specialty. Verify click-to-call Google Tag Manager firing.',
    reason: 'Conversion rate rose from 0.03% to 0.09% when form friction was minimized. Further streamlining will unlock 0.15%+.',
    priority: 'medium',
    owner: 'CRO / Web Developer',
    status: 'in_progress',
    impactEstimate: '+35% Mobile Lead Form Completion Rate',
    customNotes: 'A/B test live on Knee Ready landing page.',
    updatedAt: '2026-08-24T16:00:00Z'
  }
];

export const AI_SYNTHESIS_BASE = {
  sprintScore: 84,
  totalIdentifiedWaste: 131024,
  projectedTargetConversions: 100,
  executiveBrief: "The August 1-23 advertising cycle shows a tale of two channels: high-velocity Performance Max campaigns are delivering world-class efficiency (CPA as low as ₹2,464 on Kilpauk), while broad Search campaigns are hemorrhaging budget on runaway CPCs (up to ₹121.50). With ₹3.09L remaining for the 7-day sprint, pausing 2 inactive search campaigns and funneling funds to Kilpauk & Knee Ready PMax will comfortably double weekly patient acquisitions to 100+.",
  insights: [
    {
      id: 'insight_waste_quantified',
      category: 'waste',
      severity: 'critical',
      badge: 'Critical Budget Leakage',
      title: '₹1.31L Consumed by Zero/Low Converting Search Keywords',
      metricSummary: '₹1,31,024 spent across 3 campaigns yielded only 1 conversion',
      narrative: 'Knee Ready Search (₹37.8k spent, 0 conversions) and Tirunelveli Oncology (₹56.1k spent, 1 conversion) along with search broad matches have absorbed over 20% of the entire monthly hospital budget without meaningful patient acquisition.',
      action: 'Pause campaigns immediately and reallocate capital to Kilpauk PMax.'
    },
    {
      id: 'insight_channel_arbitrage',
      category: 'channel_divergence',
      severity: 'positive',
      badge: '40x Channel Efficiency Gap',
      title: 'PMax Outperforms Search by 40x on Knee Replacement',
      metricSummary: 'PMax ₹1.89 CPC (5 Conv) vs Search ₹75.90 CPC (0 Conv)',
      narrative: 'For the Knee Ready campaign, Performance Max delivered clicks at ₹1.89 with 5 recorded patient bookings, whereas traditional Search charged ₹75.90 per click with zero conversions.',
      action: 'Scale Knee Ready PMax daily budget from ₹1.5k to ₹6k.'
    },
    {
      id: 'insight_velocity_improvement',
      category: 'performance_drop',
      severity: 'positive',
      badge: 'Optimization Velocity',
      title: 'Weekly CPA Slashed by 58% Over 3 Consecutive Weeks',
      metricSummary: 'CPA dropped from ₹24,713 (W1) → ₹17,500 (W2) → ₹10,305 (W3)',
      narrative: 'Baseline optimizations are working. Conversion rate has steadily climbed from 0.03% to 0.09%. Continued pruning of inefficient keywords will push overall account CPA below the ₹5,000 threshold.',
      action: 'Maintain negative keyword pruning cadence.'
    },
    {
      id: 'insight_call_quality_anomaly',
      category: 'call_quality',
      severity: 'warning',
      badge: 'Call Intent Discrepancy',
      title: 'Tondiarpet PMax Generated 68 Calls But Only 1.8 Real Conversions',
      metricSummary: '68 phone calls resulted in ₹20,192 CPA',
      narrative: 'While phone calls appear high on paper, hospital reception records indicate high volumes of non-booking queries (general enquiry, job inquiries, pharmacy questions) falsely inflating conversion signals.',
      action: 'Filter search themes and exclude non-patient keywords.'
    }
  ]
};
